### ISSUE TITLE
Test Safety light using arduino

### ISSUE THREAD

**Issue by mikebowyer** [iscumd/IGVC2016#6]
Investigate if solid/flashing function of light works using just arduino.

If so then create a small tutorial on how to control the light with arduino, 

Competition rules state:
"**Safety Light:** The vehicle must have an easily viewed solid indicator light which is turned on
whenever the vehicle power is turned on. The light must go from solid to flashing whenever the
vehicle is in autonomous mode. As soon as the vehicle comes out of autonomous mode the
light must go back to solid."

**Comment by CrisAdam** [comment]
Which arduino are we using for this? (3.3v or 5v? test both?)

**Comment by mikebowyer** [comment]
Well after @CrisAdam  tested it, the light stayed on a solid color when 5V was applied to the white wire of the light. about 3.9V was the lower threshold of the light. 
It is also possible to change the mode of the yellow and blue lights in the light. Each mode changes when the 2 lights are flashed, the first only flashes yellow, the second only flashes blue, the third alternates yellow and blue, the fourth flashes them together (white).
